# Generated by Django 4.2.5 on 2023-10-02 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='product',
            new_name='products',
        ),
    ]
